### ISSUE TITLE
question

### ISSUE THREAD

**Issue by LeeHaoRanRan** [snavalm/lsr_mood_challenge_2020#1]
Hello, I would like to ask if holdout_brain is the verification data given for the given MOOD competition.
![image](https://github.com/snavalm/lsr_mood_challenge_2020/assets/143264748/7c69b51b-9479-461e-830b-a6b42182f7db)

**Comment by snavalm** [comment]
Apologies I missed this question. The holdout was a portion of the "healthy" training set that I used to evaluate training convergence. This was not the MOOD verification set
